# Generated by Django 5.1 on 2024-08-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis376', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postbox',
            name='header',
            field=models.CharField(default='Default Header', max_length=100),
        ),
    ]
